server:
  port: 8888
# Redis
spring:
  redis: 
    database: 0 
    host: localhost
    port: 6379
    password:
    timeout: 300
    pool: 
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0